// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineWallet.Infrastructure.DatabaseContext;

namespace OnlineWallet.Infrastructure.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20200606062844_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Onlinewallet.Core.Database.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currenies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "USD"
                        },
                        new
                        {
                            Id = 2,
                            Name = "JPY"
                        },
                        new
                        {
                            Id = 3,
                            Name = "BGN"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CZK"
                        },
                        new
                        {
                            Id = 5,
                            Name = "DKK"
                        },
                        new
                        {
                            Id = 6,
                            Name = "GBP"
                        },
                        new
                        {
                            Id = 7,
                            Name = "HUF"
                        },
                        new
                        {
                            Id = 8,
                            Name = "PLN"
                        },
                        new
                        {
                            Id = 9,
                            Name = "RON"
                        },
                        new
                        {
                            Id = 10,
                            Name = "SEK"
                        },
                        new
                        {
                            Id = 11,
                            Name = "CHF"
                        },
                        new
                        {
                            Id = 12,
                            Name = "ISK"
                        },
                        new
                        {
                            Id = 13,
                            Name = "NOK"
                        },
                        new
                        {
                            Id = 14,
                            Name = "HRK"
                        },
                        new
                        {
                            Id = 15,
                            Name = "RUB"
                        },
                        new
                        {
                            Id = 16,
                            Name = "TRY"
                        },
                        new
                        {
                            Id = 17,
                            Name = "AUD"
                        },
                        new
                        {
                            Id = 18,
                            Name = "BRL"
                        },
                        new
                        {
                            Id = 19,
                            Name = "CAD"
                        },
                        new
                        {
                            Id = 20,
                            Name = "CNY"
                        },
                        new
                        {
                            Id = 21,
                            Name = "HKD"
                        },
                        new
                        {
                            Id = 22,
                            Name = "IDR"
                        },
                        new
                        {
                            Id = 23,
                            Name = "ILS"
                        },
                        new
                        {
                            Id = 24,
                            Name = "INR"
                        },
                        new
                        {
                            Id = 25,
                            Name = "KRW"
                        },
                        new
                        {
                            Id = 26,
                            Name = "MXN"
                        },
                        new
                        {
                            Id = 27,
                            Name = "MYR"
                        },
                        new
                        {
                            Id = 28,
                            Name = "NZD"
                        },
                        new
                        {
                            Id = 29,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 30,
                            Name = "SGD"
                        },
                        new
                        {
                            Id = 31,
                            Name = "THB"
                        },
                        new
                        {
                            Id = 32,
                            Name = "ZAR"
                        });
                });

            modelBuilder.Entity("Onlinewallet.Core.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Onlinewallet.Core.Database.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Onlinewallet.Core.Database.Entities.Wallet", b =>
                {
                    b.HasOne("Onlinewallet.Core.Database.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Onlinewallet.Core.Database.Entities.User", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
